### ISSUE TITLE
Sent messages can be "lost"

### ISSUE THREAD

**Issue by maximilionus** [maximilionus/VectorMessenger#7]
Sent messages can be lost as the title says. This may be caused by `UDP` protocol usage or `Message Polling Thread`'s `sleep()`

**Comment by DirectDuck** [comment]
Try to mark messages with some kind of serial number. Then client can check for missing messages once in a while and request them from server.

P.S. Looks like this project don't store any messages, so for this method it should.

**Comment by maximilionus** [comment]
@DirectDuck thanks a lot, that's a really good suggestion, but it's not related to this issue. It's my fault that I described it with such minimal details and forgot to close it. Problem was originally caused by the wrong way of data transmission between server and client sockets, that caused client to be not ready for incoming data from server in some cases.

Currently, I'm fully remaking _client_ and _server_ sides of **Vector Messenger**, so there will be no such issue in future. _Client side_ is currently under development on branch [`remake`](https://github.com/maximilionus/VectorMessenger/tree/remake) _(Paused until server side will be ready)_ and _server side_ is not publicly available yet. _Server side_ will also be completely rewritten to work as a web server with database connection and public API for integrating it with _client_ on any device. That's it :)

> I will probably close this issue soon as it has nothing to do with the current stage of development.  
> And thanks again for your suggestion, I really appreciate your contribution 👍
